# Generated by Django 6.0.5 on 2026-05-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normalization', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs Clarification')], max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('reviewer', models.CharField(default='system', help_text="Who set this status ('system' for auto, future: user identifier)", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Reviewer notes, rejection reason, or clarification request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='normalization.normalizedemissionrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_statuses', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
