# Generated by Django 6.0.5 on 2026-05-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text="Activity category (e.g., 'Fuel Combustion - Diesel', 'Electricity - UK Grid')", max_length=255)),
                ('subcategory', models.CharField(blank=True, max_length=255)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 — Direct Emissions'), ('scope_2', 'Scope 2 — Indirect (Electricity)'), ('scope_3', 'Scope 3 — Value Chain')], max_length=20)),
                ('activity_unit', models.CharField(help_text="Unit of the activity value (e.g., 'liter', 'kWh', 'passenger-km', 'night')", max_length=50)),
                ('factor_value', models.DecimalField(decimal_places=6, help_text='Emission factor in kg CO2e per activity unit', max_digits=12)),
                ('factor_source', models.CharField(help_text="Publication source of this factor (e.g., 'DEFRA 2023', 'EPA GHG 2023')", max_length=255)),
                ('year', models.IntegerField(help_text='Year this emission factor applies to')),
                ('region', models.CharField(default='global', help_text="Geographic region this factor applies to (e.g., 'UK', 'US', 'global')", max_length=100)),
                ('gwp_version', models.CharField(default='AR5', help_text='IPCC Assessment Report GWP version (AR4, AR5, AR6)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scope', 'category'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=50)),
                ('to_unit', models.CharField(max_length=50)),
                ('conversion_factor', models.DecimalField(decimal_places=8, help_text='Multiply from_unit value by this factor to get to_unit value', max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['from_unit', 'to_unit'],
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(help_text="Source system type: 'sap', 'utility', or 'travel'", max_length=50)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 — Direct Emissions'), ('scope_2', 'Scope 2 — Indirect (Electricity)'), ('scope_3', 'Scope 3 — Value Chain')], max_length=20)),
                ('category', models.CharField(help_text="Activity category (e.g., 'Fuel Combustion - Diesel')", max_length=255)),
                ('subcategory', models.CharField(blank=True, max_length=255)),
                ('activity_value', models.DecimalField(decimal_places=4, help_text='Quantity of activity as reported by the source', max_digits=15)),
                ('activity_unit', models.CharField(help_text="Unit as reported by the source (may be non-canonical, e.g., 'MWh', 'gallon')", max_length=50)),
                ('normalized_value', models.DecimalField(decimal_places=4, help_text='Quantity converted to the canonical unit for this category', max_digits=15)),
                ('normalized_unit', models.CharField(help_text="Canonical unit for this category (e.g., 'kWh' for electricity, 'liter' for fuel)", max_length=50)),
                ('emission_factor_value', models.DecimalField(blank=True, decimal_places=6, help_text='Snapshot of the factor value (kg CO2e/unit) used at calculation time', max_digits=12, null=True)),
                ('co2e', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated CO2e in kg. Formula: normalized_value × emission_factor_value', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs Clarification')], default='pending_review', max_length=50)),
                ('is_suspicious', models.BooleanField(default=False, help_text='True if CO2e value is anomalous vs batch mean (flagged by ValidationService). Analysts should review these first.')),
                ('is_manually_edited', models.BooleanField(default=False, help_text='True if this record was edited after initial normalization. Triggers AuditLog entry.')),
                ('period_start', models.DateField(blank=True, help_text='Start of the activity period (billing period start, travel date, etc.)', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End of the activity period', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Source-specific metadata (plant codes, meter IDs, airport codes, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_records', to='ingestion.datasource')),
                ('emission_factor', models.ForeignKey(blank=True, help_text='The emission factor record used at calculation time', null=True, on_delete=django.db.models.deletion.SET_NULL, to='normalization.emissionfactor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='organizations.organization')),
                ('raw_record', models.OneToOneField(blank=True, help_text='The raw source row this normalized record was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized', to='ingestion.rawrecord')),
                ('upload', models.ForeignKey(blank=True, help_text='The upload batch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_records', to='ingestion.rawupload')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='normalizati_organiz_2254be_idx'), models.Index(fields=['organization', 'scope'], name='normalizati_organiz_12c9f0_idx'), models.Index(fields=['organization', 'source_type'], name='normalizati_organiz_cf62b8_idx'), models.Index(fields=['is_suspicious'], name='normalizati_is_susp_6842a1_idx')],
            },
        ),
    ]
