# Generated by Django 6.0.5 on 2026-05-25 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel/Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=50)),
                ('column_mapping', models.JSONField(default=dict, help_text='Maps source column names to canonical field names. Used to handle messy SAP exports with inconsistent headers.')),
                ('metadata', models.JSONField(default=dict, help_text='Source-specific metadata (plant codes, region, tariff type, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('file_path', models.CharField(blank=True, help_text='Server path where the original uploaded file is stored', max_length=1000)),
                ('ingestion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='ingestion.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_uploads', to='organizations.organization')),
            ],
            options={
                'ordering': ['-ingestion_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.IntegerField(help_text='Row number in the original source file (1-indexed)')),
                ('raw_data', models.JSONField(help_text='Original row data preserved verbatim from the source')),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('failed', 'Validation Failed'), ('suspicious', 'Suspicious — Flagged for Review')], default='valid', max_length=50)),
                ('error_detail', models.JSONField(blank=True, help_text="Structured error list from validation. Populated only if validation_status is 'failed' or 'suspicious'.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='organizations.organization')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.rawupload')),
            ],
            options={
                'ordering': ['upload', 'source_row_number'],
            },
        ),
    ]
