# Generated by Django 6.0.5 on 2026-05-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Django model name (e.g., 'NormalizedEmissionRecord', 'RawUpload')", max_length=100)),
                ('object_id', models.IntegerField(help_text='Primary key of the affected model instance')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('flag_suspicious', 'Flagged as Suspicious'), ('ingest', 'Ingested')], max_length=50)),
                ('old_value', models.JSONField(blank=True, help_text='State of the record before the change', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='State of the record after the change', null=True)),
                ('actor', models.CharField(default='system', help_text="Who triggered this change ('system', 'api', or future: user identifier)", max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx'), models.Index(fields=['organization', 'timestamp'], name='audit_audit_organiz_47f094_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
